#cloud-config
runcmd:
  - sudo apt update
  - sudo apt upgrade -y
  # - sudo apt install nginx -y
  # - sudo ufw allow 'Nginx HTTP'
  # - sudo systemctl enable nginx
  # - sudo adduser --disabled-password --gecos "" foundry
  # - sudo usermod -aG sudo foundry
  # - su - foundry
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
  - sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo apt-key add -
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee -a /etc/apt/sources.list.d/caddy-stable.list
  - sudo apt update
  - sudo apt install nodejs caddy unzip nano awscli -y
  - sudo npm install pm2 -g
  - pm2 startup
  - sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u foundry --hp /home/foundry
  - pm2 save
  - pm2 unstartup systemd
  - mkdir ~/foundry
  - aws s3 cp "${foundryDownloadLink}" ./foundry/foundryvtt.zip
  - unzip ~/foundry/foundryvtt.zip -d ~/foundry/
  - rm ~/foundry/foundryvtt.zip
  - pm2 start "node /home/ubuntu/foundry/resources/app/main.js --dataPath=/home/ubuntu/foundryuserdata" --name foundry
  - pm2 list
  - pm2 save
